version: 0.0
os: linux
files:
  - source: /build/package.zip
    destination: /home/ec2-user/myapp/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user
