version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - echo Dependencies installed
      - pip install pylint
      - pip install -r requirements.txt -t .

  pre_build:
    commands:
      - echo Pre-build phase
      - python -m pip install --upgrade setuptools wheel

  build:
    commands:

      - echo Building the Django app...
      - python manage.py collectstatic --noinput  
      - python manage.py migrate --noinput      
      - echo "Running pylint on jobportal and jobs modules..."
      - pylint jobportal/ jobs/ > pylint-report.txt || true
      - echo Build completed
      - zip -r build-package.zip .

  post_build:
    commands:
   
      - aws s3 cp build-package.zip s3://your-s3-bucket/path/to/your-package.zip
      - echo Post-build phase
      - echo "Build phase finished successfully"

artifacts:
  files:
    - '**/*'  
    - pylint-report.txt

cache:
  paths:
    - '/root/.cache/pip/**/*'
