version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pylint  # Install pylint for code linting

  build:
    commands:
      - python manage.py collectstatic --noinput
      - python manage.py migrate
      - echo "Running PyLint on the project..."
      - pylint --disable=R,C invoice_pro/**/*.py || true  # Run pylint on the project, disable some message categories

  post_build:
    commands:
      - echo "Zipping application files..."
      - zip -r application.zip . -x "*.git*"

artifacts:
  files:
    - application.zip
    - Procfile
    - requirements.txt
    - runtime.txt
    - .ebextensions/**  # Include EB config if present
